main: com.winthier.spawn.SpawnPlugin
name: Spawn

version: 0.1
api-version: '1.21'

description: Bring players to spawn
author: StarTux
website: https://github.com/StarTux/Spawn

depend: [Core]
softdepend: [Worlds]

commands:

  spawn:
    description: Teleport to spawn
    permission: spawn.spawn
    usage: /spawn

  setspawn:
    description: Set the spawn location.
    permission: spawn.setspawn

permissions:

  spawn.setspawn:
    description: Set the spawn location.
    default: op

  spawn.spawn:
    description: Teleport to spawn.
    default: op

  spawn.other:
    description: Teleport other players to spawn.
    default: op